### ISSUE TITLE
h2_client:send_request/3 does not check the return from h2_connection:new_stream/1,2

### ISSUE THREAD

**Issue by efine** [joedevivo/chatterbox#101]
`h2_client:send_request/3` does not check the return from `h2_connection:new_stream/1,2`. When a new stream cannot be created, for example, because the peer connection sets the maximum concurrent streams to 1, `h2_connection:new_stream/1,2` returns `{error, 7}`.

However, because `h2_client:send_request/3` does not check this, it returns `{ok, {error, 7}}` to the caller, which blows up when it next tries to use a stream id of `{error, 7}`.

**Comment by efine** [comment]
Added PR #102 to address this issue.

**Comment by tsloughter** [comment]
PR was merged, closing.
