### ISSUE TITLE
Support OTP20+

### ISSUE THREAD

**Issue by boboxiaodd** [joedevivo/chatterbox#113]
In OTP20+ gen_fsm is deprecated and replaced by gen_statem :(

**Comment by joedevivo** [comment]
It's true. I just remove the `warnings_as_errors`, which buys us some time.

**Comment by ypaq** [comment]
Bumping this thread.

**Comment by tsloughter** [comment]
@ypaq i made a PR https://github.com/joedevivo/chatterbox/pull/119

**Comment by ypaq** [comment]
@tsloughter thanks! The build seems to fail though.

**Comment by joedevivo** [comment]
I get nervous that a port to gen_statem is discontinuing support for OTP18. I'm not sure that's not ok, still... nervous
