### ISSUE TITLE
undefined parse transform 'lager_transform'

### ISSUE THREAD

**Issue by Mo33n** [joedevivo/chatterbox#116]
mix deps.compile chatterbox
===> Compiling chatterbox
===> Compiling src/h2_frame.erl failed
src/h2_frame.erl:none: undefined parse transform 'lager_transform'

** (Mix) Could not compile dependency :chatterbox, "/root/.mix/rebar3 bare compile --paths "/home/mongoosePush/MongoosePush/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile chatterbox", update it with "mix deps.update chatterbox" or clean it with "mix deps.clean chatterbox"

**Comment by tsloughter** [comment]
Lager no longer used, closing.
