### ISSUE TITLE
Should we use lager in infrastructural library?

### ISSUE THREAD

**Issue by redink** [joedevivo/chatterbox#118]
In my opinion, if something going wrong in low level library, it should throw exceptions or return error, just like : 

```
exit({something_error, "..."})
```

or

```
{error, "...."}
```

And at top level application, we could handle the error depend on our production env or log the error in our format.

If the low level app log the error information by itself, the log maybe incompatible with top level app and will cause some trouble.

In Erlang project, most developer will choose `lager` to log their error information, and they also will set the configuration about lager. So, that is fine for using lager as the file backend. But in Elixir project, Logger will be the first choice for the developer. Unfortunate, most developer will not to notice the configuration about lager. As the result, the output of file backend will be untidiness.

So, I suggest remove the `lager` and return(or throw exception) the error information to the top level app. And use `error_logger` module if log information needed. Just like cowboy:

https://github.com/ninenines/cowboy/search?utf8=%E2%9C%93&q=error_logger&type=
https://github.com/ninenines/cowboy/search?utf8=%E2%9C%93&q=lager&type=

**Comment by tsloughter** [comment]
Oh wait, forgot I already did this :)

**Comment by redink** [comment]
Thanks.
