### ISSUE TITLE
Send window size not updated on settings frames

### ISSUE THREAD

**Issue by davisp** [joedevivo/chatterbox#134]
https://github.com/joedevivo/chatterbox/blob/b73798516a2ffe591bd73526e95181582ef5376f/src/h2_stream_set.erl#L571

I'm pretty sure that's supposed to be `s/recv/send/` based on the function name and the weird behavior I'm seeing. I haven't been able to figure out a good reproducer but after narrowing it down I think its an obvious bug.

**Comment by tsloughter** [comment]
Yup, definitely should be.
