### ISSUE TITLE
Server or library?

### ISSUE THREAD

**Issue by Matti252** [joedevivo/chatterbox#139]
Hi guys!

First of all, thanks for the awesome work. I have a very basic question:

Is Chatterbox a server, or a library that is to be used by a web server? i.e. can I serve for example a REST API using Chatterbox alone, or do I need something else on top?

The project description states that Chatterbox is a server, but the README describes it as a library, so that got me confused.

Finally, if a different dependency else is needed to actually process/answer requests, could you suggest one/a few alternatives?

Thanks in advance!

**Comment by tsloughter** [comment]
Hi @Matti252, it is both a library and server (including a client). You can certainly handle requests, process and respond with chatterbox.

**Comment by Matti252** [comment]
Hi @tsloughter, that's great to hear, thanks for clarifying.

As a bonus question: do you happen to know of any project which uses Chatterbox as a server, where I could check how it looks in action?

We are evaluating which solution to use for our application, and we would like to understand how chatterbox alone compares to elli_chatterbox, or cowboy. If you have any recommendation on the best way to go, it would be very much appreciated.

**Comment by Matti252** [comment]
^To complete that, our usecase is a rest-style api, e.g. /car/53/color, /status, etc.

Thanks again!

**Comment by tsloughter** [comment]
The main project I know of that uses chatterbox is my project for GRPC https://github.com/tsloughter/grpcbox

**Comment by Matti252** [comment]
Great, we'll check it out. Thanks again for the input!
