### ISSUE TITLE
any example to receive streams on the server?

### ISSUE THREAD

**Issue by benoitc** [joedevivo/chatterbox#69]
Is it already possible to receive a stream in the server using the ranch protocol? Or maybe there another is way to do it?

In my project I could receive large bodies, and I would rather stream them than collecting everything in RAM so I can store them on the fly. Hopefully it is already possible :)

> note: on the client side I was thinking to patch it so I can pass a function to the body instead of a only binary.

**Comment by benoitc** [comment]
bump

**Comment by joedevivo** [comment]
Yes.  You need to create your own version of the `http2_stream` behavior. Then you can stream data as chunks in the body of the `on_receive_request_data/2` function. 

Does that answer your question?

**Comment by benoitc** [comment]
i guess it is , thanks :) I will play with the code this afternoon.

**Comment by benoitc** [comment]
it mostly works for me, modulo the client part I have to do in Erlang so closing the issue for now. Although one thing I want to develop are bi-directional streams. I opened #73  to continue the discussion on that topic.
