### ISSUE TITLE
http 1.1 handling

### ISSUE THREAD

**Issue by benoitc** [joedevivo/chatterbox#71]
How would you manage both HTTP 1.1 and HTTP 2?

**Comment by benoitc** [comment]
bump

**Comment by tsloughter** [comment]
I made https://github.com/tsloughter/elli_chatterbox for this.

**Comment by joedevivo** [comment]
Currently chatterbox is only handling HTTP/2. On servers that need to do both, I've sent sockets over to chatterbox if they come in with the `h2` negotiated protocol, otherwise sending them to the HTTP/1.1 server of your choice.

**Comment by benoitc** [comment]
thanks for the answers. The example with elli is what I was loiking for :)

**Comment by benoitc** [comment]
The example helped. Thanks!
