### ISSUE TITLE
bi-directional streams ?

### ISSUE THREAD

**Issue by benoitc** [joedevivo/chatterbox#73]
I have the idea to implement bi-directional streams over http2:

1) the client send a request with headers, and methods
2) The server respond with headers and wait from the client
3 we enter then in the following loop until the client or the server decide to stop:
 3.a) the client send a chunk, wait for the server
 3.b) the server  reply wioth a chun and then wait for the client
4) The server finish with a terminal trailers

Wile it can be hackish to do it with the current implement, is it even possible? Any guidance would be appreciated.

**Comment by benoitc** [comment]
here is an example in go probably more clear about what i meant:

https://github.com/golang/go/issues/13444

**Comment by benoitc** [comment]
any news about it?

**Comment by benoitc** [comment]
no answer from the maintainer since awhile. closing the issue then.

**Comment by tsloughter** [comment]
I think this might actually be supported mostly by setting `send_end_stream` to `false`.

**Comment by tsloughter** [comment]
Hm, seems on the client side I need to do more than that. It looks like it only will give response data if the stream is closed.

**Comment by tsloughter** [comment]
Looks like just a modification to how the headers are handled by the client fixes this up. Right now if the client gets headers back before it sends a body it'll error, if instead in the stream `open` state the headers are handled and remain the `open` state it can then start receiving and sending data back and forth.
