### ISSUE TITLE
http2_client is leaking processes

### ISSUE THREAD

**Issue by slezakattack** [joedevivo/chatterbox#74]
Every time an `http2_client:sync_request` is made, the client makes a new stream and adds it to the list of streams within the `http2_connection`. The stream doesn't seem to be used again, closed, or removed from the list. What's the expected result?

**Comment by palkan** [comment]
It is [closed automatically](https://github.com/joedevivo/chatterbox/blob/master/src/h2_stream.erl#L473) after receiving END_STREAM.

**Comment by tsloughter** [comment]
@palkan is right. I'm going to close this.
