### ISSUE TITLE
How do I send PING using h2_client?

### ISSUE THREAD

**Issue by arkadiyk** [joedevivo/chatterbox#89]
My firewall kills connection after 30 min idle time..

**Comment by hpopp** [comment]
Looks like `h2_connection` has a `send_frame/2` function. A ping frame can be represented with just `<<0, 0, 8, 6, 0, 0, 0, 0, 0>>`. 

In Elixir I think it would be as simple as `:h2_connection.send_frame(pid, <<0, 0, 8, 6, 0, 0, 0, 0, 0>>)`

I'm having difficulty getting any sort of ping ACK though, so no clue if it's actually working.

**Comment by joedevivo** [comment]
There's a more elegant solution, but this reply is just to help unblock whatever you're working on.

PING frames require a payload. You're just sending the frame header. The PING frame needs an 8 byte payload, which the ACK will send back for you to confirm. https://http2.github.io/http2-spec/#PING

**Comment by rslota** [comment]
This PR adds ping API: #107

**Comment by tsloughter** [comment]
Closing since the PR was merged.
