### ISSUE TITLE
Client gets an error when receives recv_h in open state

### ISSUE THREAD

**Issue by tony612** [joedevivo/chatterbox#93]
I have a fix for my problem https://github.com/tony612/chatterbox/commit/8022a12313ba0732fda673f651733830d6731bfd Without this fix, the validation will fail and client will send a RST_STREAM.

But the tests doesn't pass on my local. Are there problems with my fix?

**Comment by tsloughter** [comment]
If this particular issue wasn't already fixed it will be with #127 

I'm going to close this issue even though it isn't merged yet.
